"use client";

import React, { useState } from "react";
import { useMockData } from "../../context/MockDataContext";
import { KPICard, GlassCard } from "../../components/Card";
import {
  School,
  Users,
  BookOpen,
  DollarSign,
  Calendar,
  Send,
  ArrowRight,
  TrendingUp,
  Activity as ActivityIcon,
  CheckCircle,
} from "lucide-react";
import Link from "next/link";

export default function Dashboard() {
  const { schools, courses, activities, addActivity } = useMockData();
  const [remindersSent, setRemindersSent] = useState<Record<string, boolean>>({});

  // Calculations
  const totalSchools = schools.length;
  const activeSchools = schools.filter((s) => s.status === "Active").length;
  const totalStudents = schools.reduce((sum, s) => sum + s.studentCount, 0);
  const activeCourses = courses.length;
  const monthlyRevenue = schools
    .filter((s) => s.status === "Active")
    .reduce((sum, s) => sum + s.monthlyRevenue, 0);

  // Expiring soon (less than 30 days - e.g. July 2026 since current system time is June 25, 2026)
  const expiringSoonSchools = schools.filter((s) => {
    const expiry = new Date(s.expiryDate);
    const now = new Date("2026-06-25"); // Anchor to current context date
    const diffTime = expiry.getTime() - now.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays > 0 && diffDays <= 45; // Let's check within 45 days
  });

  const sendReminder = (schoolId: string, schoolName: string) => {
    addActivity(`Notification sent to administrative owner of ${schoolName} regarding subscription renewal.`, "Finance");
    setRemindersSent((prev) => ({ ...prev, [schoolId]: true }));
  };

  return (
    <div className="space-y-8">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <span className="text-xs font-geist font-semibold text-primary uppercase tracking-widest px-2.5 py-1 rounded-full bg-primary/10 border border-primary/20">
            Live Platform Feed
          </span>
          <h1 className="font-hanken font-bold text-4xl text-on-surface mt-2 tracking-tight">
            Systems Operational
          </h1>
          <p className="text-on-surface-variant text-sm mt-1 max-w-xl font-medium">
            All educational services across {totalSchools} global institutions are running within normal latency parameters. Monitoring {totalStudents.toLocaleString()}+ active student sessions.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={() => addActivity("Manual compliance report generated by Super Admin.", "Compliance")}
            className="px-5 py-2.5 rounded-xl text-sm font-semibold text-white bg-primary hover:bg-primary-container shadow-premium transition-all duration-200"
          >
            Generate Report
          </button>
          <button 
            onClick={() => addActivity("Audit logs viewed.", "System")}
            className="px-5 py-2.5 rounded-xl text-sm font-semibold text-on-surface bg-white border border-outline-variant hover:bg-slate-50 transition-all duration-200"
          >
            View Audit Log
          </button>
        </div>
      </div>

      {/* AI Platform Insights Banner */}
      <div className="p-6 rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50/50 to-blue-50/30 flex items-center justify-between shadow-sm relative overflow-hidden ai-glow-border ai-mesh-bg">
        <div className="flex items-start gap-4">
          <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-600 shrink-0">
            <TrendingUp size={20} />
          </div>
          <div>
            <h3 className="font-hanken font-bold text-base text-slate-900">AI Platform Insights</h3>
            <p className="text-sm text-slate-600 mt-1 max-w-xl">
              Subscription renewals are up <strong className="text-indigo-600 font-semibold">8.4%</strong> this quarter. Predicting high growth in the South Asia region for Q4 based on admin activity levels.
            </p>
          </div>
        </div>
        <Link 
          href="/superadmin/analytics" 
          className="hidden md:flex items-center gap-1.5 text-xs font-semibold text-primary hover:text-primary-container transition-colors shrink-0"
        >
          View Full Analysis <ArrowRight size={14} />
        </Link>
      </div>

      {/* KPI Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
        <KPICard
          title="Total Schools"
          value={totalSchools.toString()}
          subtext={`${activeSchools} active entities`}
          trend={{ value: "+2%", isPositive: true }}
          icon={<School size={20} />}
          variant="default"
        />
        <KPICard
          title="Active Students"
          value={`${(totalStudents / 1000).toFixed(1)}k`}
          subtext="across all courses"
          trend={{ value: "+1.6k", isPositive: true }}
          icon={<Users size={20} />}
          variant="blue"
        />
        <KPICard
          title="Active Courses"
          value={activeCourses.toString()}
          subtext="live in system"
          trend={{ value: "Live Now", isPositive: true }}
          icon={<BookOpen size={20} />}
          variant="default"
        />
        <KPICard
          title="Monthly Revenue"
          value={`$${(monthlyRevenue).toLocaleString()}`}
          subtext="recurring sales"
          trend={{ value: "+12%", isPositive: true }}
          icon={<DollarSign size={20} />}
          variant="indigo"
        />
        <KPICard
          title="Renewals (45d)"
          value={expiringSoonSchools.length.toString()}
          subtext="priority focus"
          icon={<Calendar size={20} />}
          variant="emerald"
        />
      </div>

      {/* Charts section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <GlassCard>
          <div className="flex items-center justify-between mb-6">
            <div>
              <h3 className="font-hanken font-bold text-lg text-on-surface">School Growth</h3>
              <p className="text-xs text-on-surface-variant font-medium">Annual institutional acquisition trend</p>
            </div>
            <select className="text-xs font-semibold border border-outline-variant bg-white px-3 py-1.5 rounded-lg text-on-surface-variant focus:outline-none">
              <option>Last 12 Months</option>
              <option>Last 3 Years</option>
            </select>
          </div>
          {/* Custom SVG Line Chart */}
          <div className="h-64 w-full flex flex-col justify-between pt-4">
            <svg viewBox="0 0 500 180" className="w-full h-48 overflow-visible">
              <defs>
                <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#4f46e5" stopOpacity="0.2" />
                  <stop offset="100%" stopColor="#4f46e5" stopOpacity="0.0" />
                </linearGradient>
              </defs>
              {/* Grid lines */}
              <line x1="0" y1="30" x2="500" y2="30" stroke="#f1f5f9" strokeWidth="1" strokeDasharray="4 4" />
              <line x1="0" y1="80" x2="500" y2="80" stroke="#f1f5f9" strokeWidth="1" strokeDasharray="4 4" />
              <line x1="0" y1="130" x2="500" y2="130" stroke="#f1f5f9" strokeWidth="1" strokeDasharray="4 4" />
              {/* Line path */}
              <path
                d="M 10 130 Q 100 120 150 90 T 250 80 T 350 90 T 450 40 T 490 30"
                fill="none"
                stroke="#4f46e5"
                strokeWidth="3.5"
                strokeLinecap="round"
              />
              {/* Gradient Fill */}
              <path
                d="M 10 130 Q 100 120 150 90 T 250 80 T 350 90 T 450 40 T 490 30 L 490 160 L 10 160 Z"
                fill="url(#chartGradient)"
              />
              {/* Circles on key nodes */}
              <circle cx="150" cy="90" r="5" fill="#4f46e5" stroke="#ffffff" strokeWidth="1.5" />
              <circle cx="350" cy="90" r="5" fill="#4f46e5" stroke="#ffffff" strokeWidth="1.5" />
              <circle cx="490" cy="30" r="6" fill="#3525cd" stroke="#ffffff" strokeWidth="2" />
            </svg>
            <div className="flex justify-between text-[11px] font-geist text-on-surface-variant font-medium px-2">
              <span>JAN</span>
              <span>MAR</span>
              <span>MAY</span>
              <span>JUL</span>
              <span>SEP</span>
              <span>NOV</span>
            </div>
          </div>
        </GlassCard>

        <GlassCard>
          <div className="flex items-center justify-between mb-6">
            <div>
              <h3 className="font-hanken font-bold text-lg text-on-surface">Revenue Trend</h3>
              <p className="text-xs text-on-surface-variant font-medium">Monthly recurring revenue (MRR)</p>
            </div>
            <div className="flex items-center gap-4 text-xs font-semibold text-on-surface-variant">
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-primary-container" /> Enterprise
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-secondary-container" /> Pro
              </span>
            </div>
          </div>
          {/* Custom SVG Bar Chart */}
          <div className="h-64 w-full flex flex-col justify-between pt-4">
            <svg viewBox="0 0 500 180" className="w-full h-48">
              {/* Bar 1 */}
              <rect x="30" y="80" width="30" height="80" rx="3" fill="#4f46e5" />
              <rect x="30" y="130" width="30" height="30" rx="3" fill="#39b8fd" />
              
              {/* Bar 2 */}
              <rect x="110" y="80" width="30" height="80" rx="3" fill="#4f46e5" />
              <rect x="110" y="120" width="30" height="40" rx="3" fill="#39b8fd" />

              {/* Bar 3 */}
              <rect x="190" y="70" width="30" height="90" rx="3" fill="#4f46e5" />
              <rect x="190" y="135" width="30" height="25" rx="3" fill="#39b8fd" />

              {/* Bar 4 */}
              <rect x="270" y="55" width="30" height="105" rx="3" fill="#4f46e5" />
              <rect x="270" y="100" width="30" height="60" rx="3" fill="#39b8fd" />

              {/* Bar 5 */}
              <rect x="350" y="45" width="30" height="115" rx="3" fill="#4f46e5" />
              <rect x="350" y="125" width="30" height="35" rx="3" fill="#39b8fd" />

              {/* Bar 6 */}
              <rect x="430" y="20" width="30" height="140" rx="3" fill="#4f46e5" />
              <rect x="430" y="85" width="30" height="75" rx="3" fill="#39b8fd" />
            </svg>
            <div className="flex justify-between text-[11px] font-geist text-on-surface-variant font-medium px-6">
              <span>JUL</span>
              <span>AUG</span>
              <span>SEP</span>
              <span>OCT</span>
              <span>NOV</span>
              <span>DEC</span>
            </div>
          </div>
        </GlassCard>
      </div>

      {/* Grid: Activities and Expiring Renewals */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Recent Activities */}
        <GlassCard className="lg:col-span-2">
          <div className="flex items-center justify-between mb-6">
            <h3 className="font-hanken font-bold text-lg text-on-surface flex items-center gap-2">
              <ActivityIcon size={20} className="text-primary" /> Recent Activities
            </h3>
            <button 
              onClick={() => addActivity("Super Admin audited recent activity log.", "System")}
              className="text-xs font-semibold text-primary hover:underline"
            >
              View All
            </button>
          </div>
          <div className="space-y-4">
            {activities.map((act) => {
              const categoryColor = {
                Onboarding: "bg-purple-50 text-purple-600 border-purple-100",
                Finance: "bg-blue-50 text-blue-600 border-blue-100",
                Compliance: "bg-emerald-50 text-emerald-600 border-emerald-100",
                System: "bg-slate-50 text-slate-600 border-slate-100",
              };
              return (
                <div key={act.id} className="flex items-start gap-4 p-3 rounded-xl hover:bg-slate-50/60 transition-colors border border-transparent hover:border-surface-container-highest">
                  <div className={`w-8 h-8 rounded-lg border flex items-center justify-center text-xs shrink-0 ${categoryColor[act.category]}`}>
                    {act.category[0]}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-slate-800 leading-snug">{act.text}</p>
                    <div className="flex items-center gap-2 mt-1.5">
                      <span className="text-[11px] font-geist text-slate-400">{act.timestamp}</span>
                      <span className="w-1 h-1 rounded-full bg-slate-300" />
                      <span className="text-[11px] font-geist font-medium text-slate-500 uppercase tracking-wider">{act.category}</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </GlassCard>

        {/* Expiring Soon List */}
        <GlassCard>
          <h3 className="font-hanken font-bold text-lg text-on-surface mb-1">Expiring Soon</h3>
          <p className="text-xs text-on-surface-variant font-medium mb-6">Subscriptions ending within 45 days</p>

          <div className="space-y-4">
            {expiringSoonSchools.length === 0 ? (
              <div className="p-8 text-center text-slate-400 text-sm">
                No subscription renewals pending.
              </div>
            ) : (
              expiringSoonSchools.map((s) => {
                const expiry = new Date(s.expiryDate);
                const now = new Date("2026-06-25");
                const diffTime = expiry.getTime() - now.getTime();
                const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
                const isSent = remindersSent[s.id];

                return (
                  <div key={s.id} className="p-4 rounded-xl bg-slate-50 border border-slate-200/60 flex flex-col justify-between gap-3">
                    <div className="flex items-start justify-between">
                      <div>
                        <h4 className="text-sm font-bold text-slate-800">{s.name}</h4>
                        <p className="text-xs text-slate-500 mt-0.5">{s.plan} Plan</p>
                      </div>
                      <span className={`text-[10px] font-semibold font-geist px-2 py-0.5 rounded-full border ${
                        diffDays <= 7 
                          ? "bg-rose-50 text-rose-600 border-rose-100 animate-pulse" 
                          : "bg-amber-50 text-amber-600 border-amber-100"
                      }`}>
                        {diffDays} DAYS
                      </span>
                    </div>
                    <div className="flex items-center justify-between text-xs text-slate-500 mt-1 border-t border-slate-200/40 pt-2">
                      <span>Monthly fee</span>
                      <strong className="text-slate-800">${s.monthlyRevenue}/mo</strong>
                    </div>
                    <button
                      onClick={() => sendReminder(s.id, s.name)}
                      disabled={isSent}
                      className={`w-full py-2 px-3 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all duration-200 ${
                        isSent
                          ? "bg-emerald-50 text-emerald-600 border border-emerald-200 cursor-not-allowed"
                          : "bg-white hover:bg-slate-100 text-slate-700 border border-slate-300"
                      }`}
                    >
                      {isSent ? (
                        <>
                          <CheckCircle size={14} /> Sent Reminder
                        </>
                      ) : (
                        <>
                          <Send size={13} /> Send Reminder
                        </>
                      )}
                    </button>
                  </div>
                );
              })
            )}
          </div>
        </GlassCard>
      </div>
    </div>
  );
}
